name: define_env
description: Generate dart defines from .env file and print
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  console: ^4.1.0
  dotenv: ^3.0.0

#dev_dependencies: