name: define_env
description: >
  Load environment variables from a `.env` file and converts it into a dart-define string. You can
  optionally copy the config to VS Code, Android Studio Run Configurations or to the clipboard.
version: 0.2.0
homepage: https://github.com/ibrahim-mubarak/define-env

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  console: ^4.1.0
  dotenv: ^3.0.0
  xml: ^5.1.2

dev_dependencies:
  test: ^1.17.7
