name: define_env
description: >
  Load variables from a `.env` file into a dart-define string and copy it to your IDE Config or to the clipboard.
version: 0.2.0+1
homepage: https://github.com/ibrahim-mubarak/define-env

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  console: ^4.1.0
  dotenv: ^3.0.0
  xml: ^5.1.2

dev_dependencies:
  test: ^1.17.7
